// <auto-generated />
namespace TPMascotas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class asdasda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asdasda));
        
        string IMigrationMetadata.Id
        {
            get { return "201907140440067_asdasda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
